- hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    
    - name: password
      prompt: What is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true
  vars:
    ssh_vars:
      port: 22
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        clean: yes
    
    - name: Create a user {{ username }} with a home directory
      user:
        name: "{{ username }}"
        groups: sudo
        shell: /bin/bash
        password: "{{ password }}"

    - name: Add ssh public key to user
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', 'pub/key.pub') }}"

    - name: Add Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: true