- hosts: all
  vars_prompt:
    - name: sshport
      prompt: What is your ssh port?
      private: false
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        clean: yes
      become: true

    - name: Install sudo
      apt:
        name: sudo
        state: present
      become: true

    - name: Install htop
      apt:
        name: htop
        state: present
      become: true

    - name: Replace Port in sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: ^(# *)?Port
        line: Port {{ sshport }}
      become: true
    
    - name: Replace PermitRootLogin in sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: ^(# *)?PermitRootLogin (yes|without-password|forced-commands-only|no)
        line: PermitRootLogin no
      become: true

    - name: Replace PasswordAuthentication in sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: ^(# *)?PasswordAuthentication (yes|no)
        line: PasswordAuthentication no
      become: true

    - name: Replace LoginGraceTime in sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: ^(# *)?LoginGraceTime
        line: LoginGraceTime 1m
      become: true

    - name: Replace MaxAuthTries in sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regex: ^(# *)?MaxAuthTries
        line: MaxAuthTries 3
      become: true

    - name: Install iptables persistent
      apt:
        name: iptables-persistent
        state: present
      become: true

    - name: Add Iptables input to loopback
      shell: iptables -A INPUT -i lo -j ACCEPT
      become: true

    - name: Add Iptables established connection
      shell: iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      become: true

    - name: Add Iptables ssh port {{ sshport }}
      shell: iptables -A INPUT -p tcp --dport {{ sshport }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
      become: true

    - name: Change Iptables policy input to Drop
      shell: iptables --policy INPUT DROP
      become: true

    - name: Save Iptables to persistent
      shell: netfilter-persistent save
      become: true