- hosts: all
  become: true
  become_method: su
  become_user: root

  vars_prompt:
    - name: username
      prompt: what is your username?
      private: false

    - name: user_password
      prompt: what is your password?
      private: true
      encrypt: sha512_crypt
      confirm: true

    - name: sshport
      prompt: what is your SSH port?
      private: false
      default: '22'

  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64
    public_keys:
      - files/id_rsa.pub

  roles:
    - common
    - create-user
    - ssh
    - firewall