- name: Check if /swapfile exists
  stat:
    path: /swapfile
  register: swapfile_stat

- name: Fail if /swapfile already exists
  fail:
    msg: "/swapfile already exists. Aborting to avoid overwrite."
  when: swapfile_stat.stat.exists

- name: Allocate the swap file
  command: fallocate -l {{ swap_size }} /swapfile
  when: not swapfile_stat.stat.exists

- name: Set permissions on the swap file
  file:
    path: /swapfile
    mode: '0600'

- name: Format the swap file
  command: mkswap /swapfile
  when: not swapfile_stat.stat.exists

- name: Enable the swap file
  command: swapon /swapfile
  when: not swapfile_stat.stat.exists

- name: Ensure swap file entry is present in /etc/fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
    sysctl_set: yes
    reload: yes