- name: Ensure util-linux is installed (provides mkswap)
  apt:
    name: util-linux
    state: present
    update_cache: yes

- name: Find mkswap command
  ansible.builtin.command: "which mkswap"
  register: mkswap_path
  changed_when: false
  ignore_errors: true

- name: Find swapon command
  ansible.builtin.command: "which swapon"
  register: swapon_path
  changed_when: false
  ignore_errors: true

- name: Check if /swapfile exists
  stat:
    path: /swapfile
  register: swapfile_stat

- name: Fail if /swapfile already exists
  fail:
    msg: "/swapfile already exists. Aborting to avoid overwrite."
  when: swapfile_stat.stat.exists

- name: Allocate the swap file
  command: fallocate -l {{ swap_size }} /swapfile
  when: not swapfile_stat.stat.exists

- name: Set permissions on the swap file
  file:
    path: /swapfile
    mode: '0600'

- name: Format the swap file
  command: "{{ mkswap_path.stdout | default('/sbin/mkswap') }} /swapfile"
  when: not swapfile_stat.stat.exists

- name: Enable the swap file
  command: "{{ swapon_path.stdout | default('/sbin/swapon') }} /swapfile"
  when: not swapfile_stat.stat.exists

- name: Ensure swap file entry is present in /etc/fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
    sysctl_set: yes
    reload: yes