- name: Set SSH port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: "Port {{ sshport }}"
    state: present

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin '
    line: "PermitRootLogin no"
    state: present

- name: Disable password SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication '
    line: "PasswordAuthentication no"
    state: present

- name: Set SSHD LoginGraceTime
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LoginGraceTime '
    line: "LoginGraceTime 1m"
    state: present

- name: Set SSHD MaxAuthTries
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries '
    line: "MaxAuthTries 3"
    state: present