- name: Upgrade all apt packages to latest and autoremove
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    clean: yes

- name: Install utilities (sudo, htop, curl, git)
  apt:
    name:
      - sudo
      - htop
      - curl
      - git
    state: present